apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nekocafe.fullname" . }}-secret
type: Opaque
stringData:
  DATABASE_URL: "replace-with-github-secret-or-vault-value"
  REDIS_URL: "replace-with-github-secret-or-vault-value"
