apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nekocafe.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: reservation
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nekocafe.fullname" . }}-member
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: member
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
